#!/usr/bin/env bash
# Rotates the TOUCHSCREEN to match the rotated SCREEN.
#
# wlr-randr --transform turns the picture. It does not turn the digitiser:
# the panel keeps reporting a touch at the physical spot the finger landed,
# in its own un-rotated coordinate space. With the image turned 90 degrees
# those two no longer agree, so a tap registers somewhere else entirely --
# sometimes on a different control, sometimes on nothing. It reads as "the
# screen is laggy and half my taps do nothing".
#
# libinput can transform the coordinates before anyone sees them, via the
# LIBINPUT_CALIBRATION_MATRIX udev property. That is what this sets. It runs
# as root from onefinity-kiosk.service (ExecStartPre=+) because /run/udev and
# `udevadm trigger` are not writable by the kiosk user.
#
# If touch ends up rotated the WRONG way (taps mirrored, or off by 90 the
# other direction), the compositor is already applying the transform itself
# and this is doubling it: set KIOSK_TOUCH_TRANSFORM=normal in
# /etc/onefinity-kiosk.conf and reboot.
set -u

CONF=/etc/onefinity-kiosk.conf
RULE=/run/udev/rules.d/99-onefinity-touch.rules

[ -r "$CONF" ] && . "$CONF"
KIOSK_ROTATE="${KIOSK_ROTATE:-normal}"
# auto = follow the screen rotation. normal = leave touch alone.
KIOSK_TOUCH_TRANSFORM="${KIOSK_TOUCH_TRANSFORM:-auto}"

case "$KIOSK_TOUCH_TRANSFORM" in
    auto)              TRANSFORM="$KIOSK_ROTATE" ;;
    normal|90|180|270) TRANSFORM="$KIOSK_TOUCH_TRANSFORM" ;;
    *)
        echo "onefinity-touch: KIOSK_TOUCH_TRANSFORM='$KIOSK_TOUCH_TRANSFORM' not understood; leaving touch alone" >&2
        TRANSFORM=normal
        ;;
esac

# Row-major 2x3 matrices, the standard libinput values.
case "$TRANSFORM" in
    90)  MATRIX="0 -1 1 1 0 0" ;;
    180) MATRIX="-1 0 1 0 -1 1" ;;
    270) MATRIX="0 1 0 -1 0 1" ;;
    *)   MATRIX="" ;;   # normal: no rule at all
esac

mkdir -p /run/udev/rules.d

if [ -z "$MATRIX" ]; then
    rm -f "$RULE"
else
    # ID_INPUT_TOUCHSCREEN is set by udev's own input_id builtin, so this
    # matches the real digitiser and not a mouse, keyboard or the gamepad.
    cat > "$RULE" <<EOF
# Generated by onefinity-touch-rotate from $CONF (KIOSK_ROTATE=$KIOSK_ROTATE,
# KIOSK_TOUCH_TRANSFORM=$KIOSK_TOUCH_TRANSFORM). Do not edit: rewritten at boot.
ACTION=="add|change", ENV{ID_INPUT_TOUCHSCREEN}=="1", ENV{LIBINPUT_CALIBRATION_MATRIX}="$MATRIX"
EOF
fi

# Re-apply to the already-enumerated touchscreen; without this the property
# only lands on devices plugged in after boot.
udevadm control --reload-rules 2>/dev/null || true
udevadm trigger --subsystem-match=input --action=change 2>/dev/null || true
udevadm settle --timeout=5 2>/dev/null || true

echo "onefinity-touch: transform=$TRANSFORM matrix='${MATRIX:-identity}'" >&2
exit 0
